"""Shared configuration for optional NanoTrack mask trackers."""

from .backend import (
    MASK_TRACKER_BACKEND_REGISTRY,
    MaskTrackerBackendCancelledError,
    MaskTrackerBackendError,
    MaskTrackerBackendTimeoutError,
    MaskTrackerBackendUnavailableError,
    MaskTrackerSubprocessBackend,
    create_mask_tracker_backend,
    validate_mask_tracker_backend_config,
)
from .config import (
    DAM4SAM_TRACKER_VARIANTS,
    DEFAULT_DAM4SAM_CHECKPOINT,
    DEFAULT_DAM4SAM_MODELS_DIR,
    DEFAULT_DAM4SAM_PYTHON,
    DEFAULT_DAM4SAM_REPO_PATH,
    DEFAULT_DAM4SAM_TRACKER_VARIANT,
    DEFAULT_SAM2_CHECKPOINT,
    DEFAULT_SAM2_MODELS_DIR,
    DEFAULT_SAM2_PYTHON,
    DEFAULT_SAM2_REPO_PATH,
    DEFAULT_SAMURAI_CHECKPOINT,
    DEFAULT_SAMURAI_MODEL_VARIANT,
    DEFAULT_SAMURAI_MODELS_DIR,
    DEFAULT_SAMURAI_PYTHON,
    DEFAULT_SAMURAI_REPO_PATH,
    MASK_TRACKER_KINDS,
    SAMURAI_MODEL_VARIANTS,
    MaskTrackerBackendConfig,
    MaskTrackerKind,
    checkpoint_name_for_kind,
    config_identifier_for_kind,
    default_mask_tracker_config,
)
from .contract import (
    MASK_TRACKER_CONTRACT_VERSION,
    MaskTrackerRunInput,
    MaskTrackerRunOutput,
)
from .sam2_adapter import (
    Sam2MaskTrackerBackend,
    mask_output_from_sam2_run_output,
    sam2_backend_config_from_mask_config,
    sam2_run_input_from_mask_input,
)

__all__ = [
    "DAM4SAM_TRACKER_VARIANTS",
    "DEFAULT_DAM4SAM_CHECKPOINT",
    "DEFAULT_DAM4SAM_MODELS_DIR",
    "DEFAULT_DAM4SAM_PYTHON",
    "DEFAULT_DAM4SAM_REPO_PATH",
    "DEFAULT_DAM4SAM_TRACKER_VARIANT",
    "DEFAULT_SAM2_CHECKPOINT",
    "DEFAULT_SAM2_MODELS_DIR",
    "DEFAULT_SAM2_PYTHON",
    "DEFAULT_SAM2_REPO_PATH",
    "DEFAULT_SAMURAI_CHECKPOINT",
    "DEFAULT_SAMURAI_MODEL_VARIANT",
    "DEFAULT_SAMURAI_MODELS_DIR",
    "DEFAULT_SAMURAI_PYTHON",
    "DEFAULT_SAMURAI_REPO_PATH",
    "MASK_TRACKER_KINDS",
    "MASK_TRACKER_BACKEND_REGISTRY",
    "SAMURAI_MODEL_VARIANTS",
    "MaskTrackerBackendConfig",
    "MaskTrackerBackendCancelledError",
    "MaskTrackerBackendError",
    "MaskTrackerBackendTimeoutError",
    "MaskTrackerBackendUnavailableError",
    "MaskTrackerKind",
    "MASK_TRACKER_CONTRACT_VERSION",
    "MaskTrackerRunInput",
    "MaskTrackerRunOutput",
    "MaskTrackerSubprocessBackend",
    "Sam2MaskTrackerBackend",
    "checkpoint_name_for_kind",
    "config_identifier_for_kind",
    "create_mask_tracker_backend",
    "default_mask_tracker_config",
    "mask_output_from_sam2_run_output",
    "sam2_backend_config_from_mask_config",
    "sam2_run_input_from_mask_input",
    "validate_mask_tracker_backend_config",
]
